#!/bin/bash

# Manage diaries

DIARY_PATH="$HOME/j4k1ro-stuff/DIARY"
EDITOR="vim"

if [ ! -d "$DIARY_PATH" ]; then
	mkdir -p $DIARY_PATH
fi

cd $DIARY_PATH

DIARY_NAME=
DIARY_DATE=
if [[ ! "$@" ]]; then
	DIARY_DATE="$(date +%d%m%y)"
elif [ "$1" = "on" ]; then
	if [[ "$2" =~ ^[0-9]{6}$ ]]; then
		DIARY_DATE="$2"
	else
		printf "Usage: $(basename $0) [ on <ddmmyy> | -l | latest ]\n"
		exit
	fi
elif [[ "$1" = "latest" ]]; then
	DIARY_DATE=$(ls -t $DIARY_PATH/*.dry | sed -n '1p' | egrep -o '[0-9]{6}')
else
	if [ "$1" = "-l" ]; then
		ls *.dry
		printf "\nTotal: $(ls *.dry | wc -l) diaries\n"
	else
		printf "Usage: $(basename $0) [ on <ddmmyy> | -l | latest ]\n"
	fi

	exit
fi

DIARY_NAME="note$DIARY_DATE.dry"

$EDITOR $DIARY_NAME

if [ ! -f "$DIARY_NAME" ]; then
	printf "Diary discarded. No new file added.\n"
else
	DIARY_LASTMODIFIED="$(date +%d%m%y%H%M%S -r $DIARY_NAME)"
	JUSTNOW="$(date +%d%m%y%H%M%S)"

	if [ "$JUSTNOW" != "$DIARY_LASTMODIFIED" ]; then
		printf "No modification recorded since last change.\n"
	# Take advantage of vim creating backup files when modifying existing ones
	elif [[ -f "$DIARY_NAME~" ]]; then
		printf "Diary <$DIARY_NAME> had just been modified.\n"
	else
		printf "A new diary file had just been added.\n"
	fi
fi

cd $OLDPWD
