#!/bin/bash

# Manage diaries

. j4tools

DIARY_PATH="$HOME/j4k1ro-stuff/diary"
DIARY_EDITOR="/Applications/MacVim.app/Contents/bin/vim"
DIARY_USAGE="Usage: $(basename $0) [--path] [on <ddmmyy> | latest | list]"

# Go to diary "warehouse" for easier interactions
mkdir -p $DIARY_PATH && cd $DIARY_PATH

DIARY_DATE=
PATH_FLAG=
SUBJ_FLAG=
if [[ -z "$*" ]]; then
	DIARY_DATE="$(date +%d%m%y)"
else
	while true; do
	case $1 in
		on)
			[[ $2 =~ ^[0-9]{6}$ ]] && DIARY_DATE=$2 \
				|| j4e "$DIARY_USAGE" 1
			break
			;;
		latest)
			DIARY_DATE=`ls -t *.dry | head -1 | grep -o '[0-9]\+'`
			break
			;;
		list|-l)
			if [[ -n $SUBJ_FLAG ]]; then
				SUBJ_FLAG=1
			fi
			ls -t *.dry
			j4e "\nTotal: $(ls *.dry | wc -l | bc) diaries." 0
			;;
		--path)
			PATH_FLAG=1
			shift
			;;
		--with-subjects)
			SUBJ_FLAG=1
			shift
			;;
		help|-h)
			j4e "$DIARY_USAGE" 0
			;;
		*)
			j4e "$DIARY_USAGE" 1
			;;
	esac
	done
fi

DIARY_NAME="note$DIARY_DATE.dry"

# If file exists, we are modifying its content
[[ -f "$DIARY_NAME" ]] && MOD_FLAG=1

# If file exists and --path was issued, print path to file and exit.
[[ -n $MOD_FLAG && -n $PATH_FLAG ]] && j4e "$DIARY_PATH/$DIARY_NAME" 0
if [[ -n $PATH_FLAG ]]; then
	[[ -n $MOD_FLAG ]] && j4e "$DIARY_PATH/$DIARY_NAME" 0 \
		|| j4e "$(basename $0): No context for --path"
fi

# Open the diary file
$DIARY_EDITOR $DIARY_NAME

if [[ -f "$DIARY_NAME" ]]; then
	# Compare Unix timestamp of the file last modified and current time
	if [[ "$(date -r $DIARY_NAME +%s)" != "$(date +%s)" ]]; then
		j4po "No new changes recorded for diary <$DIARY_NAME>.\n"
	elif [[ ! -z $MOD_FLAG ]]; then
		j4po "Diary <$DIARY_NAME> had just been updated.\n"
	else
		j4po "Diary <$DIARY_NAME> had just been added.\n"
	fi
else
	j4po "Diary <$DIARY_NAME> discarded. No new file added.\n"
fi

# Get back to where we were at
cd $OLDPWD
