#!/bin/bash

# Random a line in fuck database

FUCK_DATABASE="$HOME/.fuckrc"

if [[ ! -f $FUCK_DATABASE ]]
then
	printf "Fuck you!\n" > $FUCK_DATABASE
fi

if [[ "$1" = "add" ]]
then
	printf "$2\n" >> $FUCK_DATABASE
	printf "\"$2\" added to dirty words.\n"
elif [[ "$1" = "list" ]]
then
	cat $FUCK_DATABASE
elif [[ ! "$@" ]]
then
	TOTALFUCK=$(cat $FUCK_DATABASE | wc -l)
	sed -n "$((RANDOM % TOTALFUCK + 1))p" $FUCK_DATABASE
fi
