#!/bin/bash

# Random a line in fuck database

. j4tools

fuck_reply() {
	local db=$1
	local total=$(cat $db | wc -l)
	sed -n "$((RANDOM % total + 1))p" $db
	exit
}

FUCK_DATABASE="$HOME/.fuckrc"
FUCK_USAGE="Usage: $(basename $0) [add | list]"

[[ ! -f $FUCK_DATABASE ]] && printf "Fuck you!\n" > $FUCK_DATABASE
[[ -z "$*" ]] && fuck_reply $FUCK_DATABASE

case "$1" in
	+|add)
		if [[ ! -z "$2" ]]; then
			if [[ ! -z $(fgrep -x "$2" $FUCK_DATABASE) ]]; then
				j4po "Already taught about '$2'.\n"
			else
				printf "$2\n" >> $FUCK_DATABASE
				j4po "'$2' added to dirty lines collection.\n" 0
			fi
		else
			j4e "$FUCK_USAGE"
		fi
		;;
	-l|list)
		cat $FUCK_DATABASE
		;;
	*)
		j4e "$FUCK_USAGE"
		;;
esac
