#!/bin/bash

# Compile C source files with zero effort

. j4tools

j4cc_usage() {
	j4e "Usage: $(basename $0) [11|99|89] SOURCE(S) [-oOUTPUT] [-l <library> ...]" 1
}
j4cc_execute() {
	local COMMAND=$1
	printf "$COMMAND\n"
	$COMMAND
}

# Variations
# I.  Final command
#     1. gcc -Wall -Wextra -std=<STDC> *.c -o OUTPUT [-l <libraries> ...]
# II. Command-line arguments
#     1. j4cc [<STDC>] *.c [-o OUTPUT] [-l <libraries]

[[ ! "$@" ]] && j4cc_usage

STDC=
SOURCES=
LIBS=
OUTPUT=
NO_WARNINGS=
while true; do
	[[ -z $1 ]] && break
	case "$1" in
		17|11|99|90|89)
			STDC=$1
			shift ;;
		*.c)
			SOURCES="$SOURCES $1"
			shift ;;
		-l*)
			LIBS="$LIBS $1"
			shift ;;
		-o*)
			OUTPUT="$1"
			shift ;;
		--no-warn)
			NO_WARNINGS=1
			shift ;;
		*)
			j4cc_usage ;;
	esac
done

[[ -z $SOURCES ]] && j4e "Source file(s) (*.c) is missing."
[[ -z "$(ls $SOURCES 2> /dev/null)" ]] && j4e "Source file(s) doesn't exist."

COMPILER="cc"
WARNS=
[[ -z $NO_WARNING ]] && WARNS="-Wall -Wextra"
[[ -z $STDC ]] && STDC=11
[[ -z $OUTPUT ]] && OUTPUT="-o $(echo $SOURCES | cut -f 1 -d .).out"

COMMAND="$COMPILER $WARNS -std=c$STDC $SOURCES $LIBS $OUTPUT"

j4cc_execute "$COMMAND"
