#! /bin/zsh

# Quickly note something on the fly

# Exit on error
set -e

# Find editor
editor=${VISUAL:-${EDITOR:-nvim}}
if ! which $editor >/dev/null 2>&1; then exit 1; fi

# Default note location
vault=$HOME/writings/justwrite
[[ ! -d $vault ]] && mkdir -p $vault

tag=
case "$1" in
  ask)
    tag=question
    shift
    ;;
  think)
    tag=thought
    shift
    ;;
  *)
    tag=uncategorized
    ;;
esac

notefile=${vault}/$(date +"%Y%m%d%H%M%S").txt

if [[ -z "$*" ]]; then
  $editor $notefile
else
  content=$*
  [[ $tag = question ]] && content=$content'?'
  # Title is capitalized content
  title=$(python3 -c 'print("'$content'".capitalize())')
  cat > $notefile << EOF
= $title

$content

#$tag
EOF
fi

[[ -f $notefile ]] && print "Wrote $notefile" || exit 0
