#! /bin/zsh

# Switch between dark and light theme in kitty

typeset -A themes=(
	[dark]="Catppuccin-Mocha"
	[light]="Catppuccin-Latte"
)

case $(uname) in
	Linux)
		dark=$(gtk-query-settings prefer-dark-theme | grep -i true)
		;;
	Darwin)
		dark=$(defaults read -g AppleInterfaceStyle 2>/dev/null)
		;;
esac

if [[ -n $dark ]]; then
	(set -x; kitten themes ${themes[dark]})
else
	(set -x; kitten themes ${themes[light]})
fi
