#!/bin/sh

# Fetch petrol price

URL=https://www.pvoil.com.vn/truyen-thong/tin-gia-xang-dau

tmpfile=`mktemp -t pnews` || exit 1
curl -Ls $URL -o $tmpfile

printf "`grep "Giá điều chỉnh" $tmpfile | sed -E -e 's/<[^>]*>//g' -e 's/(^ *| *$)//'`\n"
printf "`grep -A1 'RON 95' $tmpfile | tr "\r\n" ' ' | sed -E -e 's/<[^>]*>//g' -e 's/(^ *| *$)//'`\n"
printf "`grep -A1 'RON 92' $tmpfile | tr "\r\n" ' ' | sed -E -e 's/<[^>]*>//g' -e 's/(^ *| *$)//'`\n"
